### ISSUE TITLE
Requesting documentation or references for the shader algorithm.

### ISSUE THREAD

**Issue by ln42** [MizunagiKB/edge_detect_shader#1]
Hi there, thanks for that great project. It works very well.

I did experiment with it, especially the `edge_detect.shader` that I would like to adapt for my game prototype. I do have some difficulty understanding how it works, as the code looks like a sobel filter but you are defining a spatial shader and then applying it on CSGMesh (using `ALPHA`).

Could you please give references or explanation about how the `edge_detect.shader` is working? did you took the algorithm from somewhere else?

I hope you'll have some time to share a bit of detail about your work, thanks!

**Comment by MizunagiKB** [comment]
My algorithm is based on the Sobel filter.

* Custom post-precessing(Godot Engine Document)
  * https://docs.godotengine.org/en/stable/tutorials/viewports/custom_postprocessing.html
* Sobel operator(WIkipedia)
  * https://en.wikipedia.org/wiki/Sobel_operator

I'm not an expert, so it may not be helpful, but I've added an explanation to README.md.

https://github.com/MizunagiKB/edge_detect_shader/blob/main/README.md

I think it is easier to understand the operating principle if you think in 1-Dimension.

**Comment by ln42** [comment]
It's super helpful!

It's a neat trick to do sobel filter using depth texture, this way you don't have to worry about lighting :+1: 

Totally noob with shader here, and just found your youtube video yesterday when researching, thank you so much for the effort in explaining your work, really appreciated :heart:
